site_name: Cardinal System
pages:
  - Home: index.md
  - About: about.md
  - SetUp: setup.md
  - '運営マニュアル':
      - '運営責任者': ./manual/organizer.md
      - '競技者係': ./manual/reception.md
theme: readthedocs    
